apiVersion: v1
kind: Service
metadata:
  name: consignment-service
spec:
  selector:
    app: consignment-service
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 31006

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: consignment-service
spec:
  selector:
    matchLabels:
      app: consignment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: consignment-service
    spec:
      containers:
        - name: server
          image: katerinamayevska/consignment-service:latest
          ports:
            - name: http
              containerPort: 8082


---